name: 自动更新接口去重

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装所有依赖
        run: |
          pip install lxml_html_clean requests requests-html gitpython aiohttp commentjson urllib3

      - name: 执行整理脚本
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python main.py

      - name: 提交并发布文件
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # 检查是否有文件变动
          git add -A
          if git diff --staged --quiet; then
            echo "没有发现文件变动，跳过提交。"
          else
            git commit -m "自动更新接口: $(date +'%Y-%m-%d %H:%M:%S')"
            # 自动推送到当前分支（兼容 main 或 master）
            git push origin HEAD
          fi
